-- Knowledge base parity fill: 5 of the original 8 Purview services
-- (data_lifecycle_management, insider_risk_management, ediscovery,
-- information_protection, communication_compliance) shipped in the Epic C
-- seed with only 1-2 knowledge_base_entries rows each, while every other
-- service in the catalog (dlp, retention, sensitivity_labels, and all 4
-- Bravo practice-area services added in migration 0015) follows a
-- consistent 3-entries-per-service pattern: two general entries plus one
-- Government/regulated-environment entry. Found via a direct query against
-- the live table while auditing "is the knowledge base up to date" —
-- not a hypothetical gap. Brings all 12 services to the same 3-entry
-- floor (28 existing rows + 8 new = 36 total).
--
-- Same first-draft-content caveat as every prior KB batch (docs/PRD.md
-- §10) — not reviewed by a compliance/technical SME.

insert into knowledge_base_entries (title, service_type, industry, content, source_url) values

('Retention Labels vs Retention Policies', 'data_lifecycle_management', null,
$content$Retention policies apply the same retain/delete behavior to every item in a location (a mailbox, a SharePoint site) and are the right default for broad, location-wide rules. Retention labels apply per-item — either user-applied, auto-applied via a policy (sensitive info types, trainable classifiers, or a keyword query), or default-applied at a library/folder level — and are the right tool when different items in the same location need different lifecycles (e.g., contracts vs. general correspondence in the same mailbox). When both a label and a policy could apply to the same item, the more restrictive retention period wins and an explicit "delete" action never overrides a "retain" from either source — explain this precedence up front so a customer doesn't assume a policy change alone can force early deletion of labeled content. Adaptive scopes (dynamic membership based on user/site attributes) reduce the maintenance burden of static scopes as an org's structure changes, and are worth recommending over static scopes for any policy expected to outlive the current org chart.$content$,
'https://learn.microsoft.com/purview/retention-regulatory-requirements'),

('Federal Records Schedules & Disposition Review', 'data_lifecycle_management', 'Government',
$content$Federal agencies must retain records per NARA-approved records schedules (agency-specific schedules or General Records Schedules for common record types), not an arbitrary retention period chosen during the engagement — confirm which schedule(s) apply to the customer's record types before designing retention labels, rather than defaulting to a generic commercial retention period. Purview's disposition review workflow (a designated reviewer approves or extends disposition before permanent deletion) should be enabled for any records schedule requiring documented disposition authority, since NARA schedules typically require a decision record, not silent auto-deletion. Records Management's "regulatory record" declaration (blocking edits and further label changes) is the appropriate control for records that must be provably unaltered — distinguish this from ordinary retention labels when a customer's schedule specifically requires records-integrity guarantees, not just a retention duration.$content$,
'https://learn.microsoft.com/purview/records-management'),

('Adaptive Protection & Sequence Detection', 'insider_risk_management', null,
$content$Adaptive Protection automatically adjusts a user's risk level (elevated, moderate, minor) based on their Insider Risk Management activity and can drive dynamic, risk-based DLP enforcement (e.g., automatically blocking exfiltration for a user who has just crossed into elevated risk) without a separate manual DLP policy change — position this as the mechanism that closes the gap between "we detected risk" and "we actually did something about it in time." Sequence detection identifies chains of related risky activities (e.g., a user searching for a competitor, then downloading files, then attempting to exfiltrate) as a single elevated-severity case rather than several disconnected low-severity alerts, which materially reduces analyst alert fatigue compared to treating each activity independently. Case investigation should route through named analysts with the Insider Risk Management Investigator/Analyst roles (not general admins) — case content is deliberately restricted and pseudonymized by default, and scoping this correctly during setup avoids a privacy/HR escalation later.$content$,
'https://learn.microsoft.com/purview/insider-risk-management-adaptive-protection'),

('eDiscovery Premium: Custodian Management & Review Analytics', 'ediscovery', null,
$content$eDiscovery (Premium) custodian management tracks legal hold notifications, acknowledgments, and reminders per custodian — recommend this over manually tracking hold acknowledgment in email or a spreadsheet for any matter with more than a handful of custodians, since Premium keeps a defensible audit trail of who was notified and when. Review set analytics (near-duplicate detection, email threading, and theme clustering) meaningfully reduce reviewer hours on large document sets by surfacing duplicates and related items together instead of requiring linear review — this is usually the strongest cost justification for Premium over Standard on a large matter. Communications review (available in Premium) reconstructs Teams/chat conversations with context rather than presenting isolated messages, which matters for matters where chat-based communication is a significant part of the evidence, not just email.$content$,
'https://learn.microsoft.com/purview/edisc-analyzing-review-sets'),

('eDiscovery for FOIA Requests and Federal Litigation Holds', 'ediscovery', 'Government',
$content$FOIA requests and litigation holds are legally distinct processes with different search, review, and exemption-redaction requirements — a FOIA response typically requires reviewing for statutory exemptions (e.g., deliberative process, personal privacy) before release, which is a different workflow than a litigation hold's preserve-and-produce obligation, and scoping should keep the two processes separate even when they touch overlapping content. Confirm GCC High or DoD tenant Advanced eDiscovery feature availability before committing to a Premium-scope deliverable for a federal customer, since feature parity with commercial eDiscovery Premium has historically lagged in government clouds — verify current availability rather than assuming commercial parity. Chain-of-custody documentation (who searched what, when, and what was exported) matters more in federal litigation and FOIA contexts than typical commercial matters — build an explicit audit-trail export step into the deliverable rather than treating it as optional.$content$,
'https://learn.microsoft.com/purview/edisc-premium-legal-holds'),

('Sensitivity Label Auto-Labeling & Trainable Classifiers', 'information_protection', null,
$content$Client-side auto-labeling (Word/Excel/Outlook applying a label as a user works) gives real-time feedback but only covers files actively opened in supported apps; service-side auto-labeling (via a Purview policy scanning SharePoint/OneDrive/Exchange) covers content at rest tenant-wide but isn't real-time — most engagements need both, not one instead of the other, and scoping should say so explicitly rather than presenting them as alternatives. Trainable classifiers (pre-trained, like "Resume" or "Source Code," or custom-trained on a sample set) are the better auto-labeling condition for content that doesn't match a clean pattern (contracts, resumes, source code); built-in sensitive information types remain the right choice for well-structured data like credit card or SSN patterns — recommend classifiers only where a SIT genuinely can't do the job, since custom classifiers need a real training sample set and ongoing accuracy review. Label inheritance during co-authoring (a lower-sensitivity label can't silently downgrade a higher one when documents are merged) should be tested explicitly with the customer's actual collaboration patterns before rollout, since Teams/SharePoint co-authoring on labeled files is a common source of unexpected labeling behavior.$content$,
'https://learn.microsoft.com/purview/apply-sensitivity-label-automatically'),

('Communication Compliance: Reviewer Workflows & Escalation', 'communication_compliance', null,
$content$Reviewer role separation matters here more than in most other Purview workloads — the person configuring policies (Communication Compliance Admin) should typically not be the same person reviewing flagged content (Communication Compliance Analyst/Investigator), since this is a workplace-monitoring capability where separation of duties is both a privacy best practice and often an HR/Legal expectation, not just a technical nicety. Remediation actions on a flagged item (mark as resolved, tag for follow-up, notify the user's manager, or escalate to a formal investigation) should be documented as a decision tree during scoping so reviewers aren't improvising a process the first time a real violation surfaces. Escalating a Communication Compliance case into a formal eDiscovery investigation preserves the item and its review history — recommend this path over manually exporting content when a case may lead to disciplinary action or litigation, since it keeps a single defensible chain of custody instead of two disconnected records.$content$,
'https://learn.microsoft.com/purview/communication-compliance-investigate-remediate'),

('Communication Compliance for Federal Conduct & Ethics Monitoring', 'communication_compliance', 'Government',
$content$Communication Compliance policies used for federal conduct/ethics monitoring (e.g., conflict-of-interest language, prohibited solicitation) should be scoped and approved through the agency's existing ethics/conduct office, not configured unilaterally by IT — this is the same separation-of-duties principle as commercial deployments, but the approving stakeholder is different and should be identified explicitly during scoping. Communication Compliance is a conduct-monitoring tool and is distinct from an Insider Threat Program under NISPOM/E.O. 13587 — the two can share underlying signals but serve different governance purposes and typically report to different offices, so avoid presenting one as a substitute for the other. Monitored communications may themselves become records subject to FOIA or litigation hold — confirm with the customer's records office whether Communication Compliance case data needs its own retention/disposition treatment rather than assuming it falls outside normal records management.$content$,
'https://learn.microsoft.com/purview/communication-compliance');
