-- Knowledge base depth expansion: the KB has sat at a flat 3-entries-per-
-- service floor since migration 0016's parity fill — every one of the 12
-- services has exactly 3 short entries and none of them are more than a
-- single-topic primer. Doubles coverage to 6 entries per service (36 new
-- rows) so the KB reads as a real practice reference across each service's
-- common engagement scenarios, not just a "what is this service" blurb.
-- Same voice/format as every prior batch: consultant-advisory guidance
-- with a specific recommendation and its rationale, not a textbook
-- definition, each citing a real Microsoft Learn (or product-docs) URL.
--
-- Same first-draft-content caveat as every prior KB batch (docs/PRD.md
-- §10) — not reviewed by a compliance/technical SME.
--
-- Note: these rows insert with embedding left null, same as all 36
-- existing rows (verified via direct query — none of the current KB has
-- ever been embedded in this environment, since no AI provider key is
-- configured here). Production's create/update path best-effort-generates
-- an embedding on every save (src/lib/knowledge-base/service.ts), so each
-- row picks one up the next time it's edited through the admin UI; there
-- is no separate backfill job. Flagging this rather than silently leaving
-- it — semantic search (migration 0022) has had nothing to rank against
-- for any KB entry, real or new, and has been silently falling back to
-- tag-filtering the whole time.

insert into knowledge_base_entries (title, service_type, industry, content, source_url) values

-- dlp
('DLP for Endpoint (Windows/macOS)', 'dlp', null,
$content$Endpoint DLP extends policy enforcement to activity a cloud-only DLP policy can't see — copying a sensitive file to USB, printing it, or pasting its contents into an unallowed app or browser upload — via the same Purview endpoint agent that also feeds Insider Risk Management and Adaptive Protection. Scope endpoint policies to onboarded, Defender-for-Endpoint-enrolled devices explicitly during design; a customer that assumes endpoint coverage is automatic once a cloud DLP policy exists will have a real enforcement gap on unmanaged or not-yet-onboarded machines. Unallowed browser and unallowed app lists need active maintenance as the customer's own app landscape changes — treat this as an operational runbook item, not a one-time configuration, or the policy quietly degrades as new SaaS tools show up in the environment.$content$,
'https://learn.microsoft.com/purview/endpoint-dlp-learn-about'),

('Exact Data Match (EDM) for Structured Sensitive Data', 'dlp', null,
$content$Exact Data Match trains a DLP policy against the customer's actual structured data (a hashed database export of real customer/employee/account numbers) rather than a generic pattern, which is the right recommendation whenever built-in sensitive information types produce too many false positives on a customer's specific ID formats — a 9-digit internal account number that also happens to match a generic SIT pattern, for example. EDM requires the customer to periodically re-upload a refreshed data set as their underlying records change, and does not detect data that's been transformed (reformatted, partially redacted) beyond what the schema tolerates — set this expectation early rather than positioning EDM as a drop-in replacement for every SIT false-positive problem. The data upload and schema definition happen through the Security & Compliance PowerShell module, not the portal UI alone, so budget setup time accordingly in the deliverable.$content$,
'https://learn.microsoft.com/purview/sit-learn-about-exact-data-match-based-sits'),

('DLP Incident Response & Alert Triage Workflow', 'dlp', null,
$content$A DLP rollout is incomplete without a documented alert-triage workflow — who reviews DLP alerts, what severity routes to immediate investigation versus weekly review, and how a confirmed incident escalates to HR/Legal — and this should be a deliverable section, not an assumption the customer already has a process. Policy tips (the in-app warning shown to the end user at the moment of a policy match) meaningfully reduce incident volume by catching accidental oversharing before it becomes a real incident, and should be enabled in most policies rather than reserved only for the strictest ones. Start new or materially changed policies in test mode (or with policy tips only, no blocking) before enforcing block actions — jumping straight to enforcement on an untuned policy is the single most common cause of a DLP rollout generating enough false-positive user friction to get the whole program pushed back.$content$,
'https://learn.microsoft.com/purview/dlp-learn-about-dlp'),

-- retention
('Retention for Teams, Yammer, and Viva Engage', 'retention', null,
$content$Teams chat and channel messages, and Yammer/Viva Engage community posts, follow different underlying storage and retention mechanics than mailbox or SharePoint content, so a retention policy scoped only to "Exchange and SharePoint" silently leaves chat-based collaboration ungoverned — confirm Teams and Yammer locations are explicitly included whenever a customer's retention requirement is meant to be organization-wide, not assumed. Teams private chat retention operates per-user against a hidden substrate mailbox, while channel messages retain against the team's group mailbox — this distinction matters when explaining to a customer why a chat retention report doesn't map cleanly to individual user mailboxes. Viva Engage (formerly Yammer) native mode communities follow Microsoft 365 Groups-based retention like Teams; a customer still on Yammer's original network-wide mode needs a separate conversation about migrating to native mode before modern retention/eDiscovery coverage applies.$content$,
'https://learn.microsoft.com/purview/retention-policies-teams'),

('Disposition Review & Defensible Deletion Workflow', 'retention', null,
$content$Disposition review is the human checkpoint between a retention label's timer expiring and the item actually being deleted — a reviewer is notified, can extend, relabel, or approve deletion, and the decision is recorded — and should be enabled for any records category where a customer needs to prove disposition was a deliberate, documented act rather than silent auto-purge. Multi-stage disposition (a second reviewer or a different review stage) is available for records requiring a higher bar of documented authority; recommend it only where the customer's own records-retention policy or a regulator actually requires it, since each added stage is real ongoing reviewer workload. Items that pass disposition review without an explicit "delete" decision remain in place, not deleted by default — make sure customer reviewers understand a disposition queue that isn't actively worked doesn't fail open into deletion, which is a common and understandable misconception.$content$,
'https://learn.microsoft.com/purview/disposition-reviews'),

('File Plan Manager for Bulk Retention Label Taxonomy', 'retention', null,
$content$File Plan Manager is the right tool for importing or bulk-editing a large retention label taxonomy (tens to hundreds of labels mapped to a customer's existing records schedule) via CSV rather than creating labels one at a time in the portal UI — recommend it as soon as an engagement's label count moves into the dozens, since manual creation at that scale is both slow and error-prone on the metadata fields (retention period, trigger, disposition action) that actually drive behavior. File plan descriptors (department, category, citation, authority) don't change label behavior themselves, but are what makes a large taxonomy navigable and auditable for the customer's records team after handoff — populate them deliberately rather than leaving them blank to save time during the engagement, since that cost lands on the customer later. Label publishing to locations is a separate step from label creation in File Plan Manager — a common gap is a fully built taxonomy that was never actually published to the mailboxes/sites where it needs to apply.$content$,
'https://learn.microsoft.com/purview/file-plan-manager'),

-- sensitivity_labels
('Label Scopes and Priority Ordering', 'sensitivity_labels', null,
$content$A sensitivity label's scope (files & emails, containers — Teams/SharePoint/groups, Power BI, schematized data assets) determines where it can be applied and which protection settings are even available to configure — a label meant to restrict a Teams site needs the container scope enabled, which is easy to miss if a taxonomy is designed only around document protection. Label order in the admin center determines priority when a user sees the label picker, and separately determines which label wins on the rare case of a conflicting programmatic application — design a deliberate low-to-high sensitivity order early, since reordering after user training and muscle memory has formed on picker position causes real adoption friction. A label scoped to multiple asset types (e.g., both files/emails and containers) shares one name and priority across all of them; where a customer's needs genuinely diverge between document protection and container-level governance, that's a signal for two labels, not one label doing double duty.$content$,
'https://learn.microsoft.com/purview/sensitivity-labels'),

('Mandatory Labeling and Default Label Rollout Strategy', 'sensitivity_labels', null,
$content$Mandatory labeling (blocking save/send until a label is applied) and a default label (auto-applied but changeable) solve different adoption problems and are frequently confused during scoping — default label gets baseline coverage on content users wouldn't have labeled themselves with zero added friction, while mandatory labeling guarantees no unlabeled content exists but adds a real interaction to every save/send, and most rollouts benefit from starting with a default label and introducing mandatory labeling later once users are already comfortable with the picker. Turning on mandatory labeling before running a pilot with real end users is a common cause of rollout pushback — recommend a phased sequence (default label first, measure adoption, then mandatory) over flipping mandatory on for the whole tenant on day one. Label policies can target specific user/group scopes independently of the labels themselves, so a phased rollout by department or pilot group doesn't require separate label definitions — only separate policy assignments.$content$,
'https://learn.microsoft.com/purview/create-sensitivity-labels'),

('Double Key Encryption for Highly Regulated Content', 'sensitivity_labels', 'Government',
$content$Double Key Encryption (DKE) requires two keys to decrypt protected content — one Microsoft-managed in Azure, one the customer holds entirely outside Microsoft's control — and is the right recommendation only for the narrow set of content where a customer's own compliance posture requires that Microsoft itself never have technical access to decrypt it, not as a default protection setting. DKE trades away most of the collaboration and search/indexing functionality that makes labeled content usable day to day (no eDiscovery content search inside DKE-protected files, no co-authoring, limited mobile support), so scope it deliberately to the specific document population that needs it rather than applying it broadly out of an abundance of caution. Hold Your Own Key (HYOK, an older on-premises-AD-RMS-based approach) is a distinct, largely legacy mechanism from DKE — confirm which one a customer means when "we need to hold our own keys" comes up in a Government/regulated scoping conversation, since the guidance and effort differ significantly between them.$content$,
'https://learn.microsoft.com/purview/double-key-encryption'),

-- data_lifecycle_management
('Event-Based Retention for Lifecycle Triggers', 'data_lifecycle_management', null,
$content$Event-based retention starts a retention/deletion clock from a defined business event (contract expiration, employee termination, product end-of-life) rather than from content creation or last-modified date, and is the right recommendation whenever a customer's actual retention requirement is expressed in terms of "N years after X happens" rather than a flat age-based window. Setting up an event type and asset relationships (which labeled items belong to which event) is meaningfully more setup work than a standard time-based label, so scope it only for record categories where the business genuinely needs trigger-based timing — most retention requirements are still simpler flat time windows that don't need this. Event-based retention requires someone (a records manager, typically) to actually trigger the event when it occurs; it isn't automatically detected from HR or contract systems out of the box, so the customer's operational process for triggering events is as important a deliverable as the label configuration itself.$content$,
'https://learn.microsoft.com/purview/event-driven-retention'),

('Regulatory Records and File Plan Declaration', 'data_lifecycle_management', 'Government',
$content$Declaring content a "regulatory record" (versus an ordinary record label) locks it against further edits, renaming, and even further retention-period changes without a documented process — recommend it specifically for record categories where the customer's regulatory schedule requires provable content integrity, not as a blanket setting for every records label, since it also blocks legitimate corrections without an override workflow. A regulatory record's retention period effectively can't be shortened once declared (only extended), which is a deliberate one-way door — make sure the customer's records office signs off on which categories get this treatment before it ships, since walking it back requires Microsoft support involvement, not a self-service admin change. File plan metadata (citation, authority, department) tying a label back to the specific records schedule it satisfies is what makes a records-management program defensible to an auditor later — treat completing it as part of the deliverable, not optional documentation.$content$,
'https://learn.microsoft.com/purview/records-management'),

('Bulk Retention Label Application at Scale', 'data_lifecycle_management', null,
$content$Applying retention labels to a large existing content population (a multi-year SharePoint document library, a mail-enabled shared mailbox archive) is a distinct scoping item from designing the label taxonomy itself — bulk application via Content Explorer/Content Search-based label application, or a Microsoft 365 admin API script, moves fundamentally slower than the taxonomy design conversation, and should be estimated and communicated as its own phase with its own timeline. Auto-apply policies (trainable classifier or sensitive-info-type-driven) can retroactively label existing content, not just new content going forward, but they run as a background service over the target locations at Microsoft's own pace — set the customer's expectations that a large backlog can take days to weeks to fully process, not hours. Confirm label conflicts on already-labeled content before a bulk operation; a bulk auto-apply policy that overwrites a user's manually chosen label with a lower-priority auto-applied one is a frequent, avoidable source of a rollout's first support escalation.$content$,
'https://learn.microsoft.com/purview/apply-a-retention-label-automatically'),

-- insider_risk_management
('IRM Indicators and Data Connectors', 'insider_risk_management', null,
$content$Insider Risk Management's signal quality is only as good as the indicators and data connectors actually enabled — beyond native Microsoft 365 activity (DLP alerts, file/email exfiltration patterns, unusual download volume), connectors for HR systems (resignation/termination dates) and physical security/badge data materially improve detection of the highest-value insider risk scenario, a departing employee, by correlating digital activity against a known risk window rather than treating every user as equally likely to be a risk at any time. Scope which indicators are actually enabled explicitly during design — IRM ships with indicators turned off by default in several categories, and a policy built on a narrower indicator set than the customer assumes is a common source of "why didn't this catch X" after the fact. Third-party connectors (non-Microsoft HR/security systems) require the customer's own data engineering effort to feed IRM in the expected format — flag this as a dependency and realistic timeline risk early, not something IRM configuration alone resolves.$content$,
'https://learn.microsoft.com/purview/insider-risk-management-settings'),

('Privacy-by-Design: Pseudonymization and Role Separation', 'insider_risk_management', null,
$content$Insider Risk Management pseudonymizes user identities in case alerts and investigations by default, showing a masked identifier rather than a real username until an authorized reviewer with the correct role explicitly un-masks it and that action is itself logged — position this as the feature that makes IRM defensible to a works council, union, or privacy office, not an optional setting to consider disabling for convenience. Role separation between IRM Admins (who configure policies) and IRM Analysts/Investigators (who review pseudonymized alerts and escalate cases) mirrors the same separation-of-duties principle used in Communication Compliance, and should be staffed with genuinely different people wherever the customer's org size allows it — a single person holding both roles undermines the privacy story the pseudonymization feature is meant to support. Loop in the customer's HR, Legal, and (where applicable) works council or employee-relations stakeholders during scoping, not just IT/Security — IRM is one of the few Purview workloads where the primary blocker to a successful rollout is usually organizational buy-in, not technical configuration.$content$,
'https://learn.microsoft.com/purview/insider-risk-management-privacy'),

('IRM Analytics for Pre-Policy Risk Assessment', 'insider_risk_management', null,
$content$IRM Analytics runs a privacy-protective, aggregate-only scan across the tenant before any policy is turned on, surfacing organization-wide risk trend indicators (volume of potential data exfiltration activity, users matching risky-activity patterns) without identifying individuals — recommend running this first in any new IRM engagement, both to build the business case for which policy templates matter most to this specific customer and to set a defensible, data-driven baseline rather than guessing which risk scenarios to prioritize. Analytics results should directly inform indicator and policy-template selection (departing employee, data leaks, data theft by departing users, security policy violations) rather than enabling every available template by default — an over-broad policy set generates alert volume the customer's (often small) IRM review team can't realistically work through, which undermines the program faster than under-coverage would. Re-run Analytics periodically post-rollout, not just once at kickoff — it's a useful ongoing signal for whether policy tuning is keeping pace with how the organization's actual risk profile is changing.$content$,
'https://learn.microsoft.com/purview/insider-risk-management-analytics-scenarios'),

-- ediscovery
('Legal Hold Notification and Custodian Communication', 'ediscovery', null,
$content$eDiscovery (Premium) custodian management automates hold notifications, acknowledgment tracking, and configurable reminder cadences per custodian, and should be the default recommendation over ad hoc email notifications for any matter with enough custodians that manually tracking acknowledgment becomes a real defensibility risk — an unacknowledged hold with no documented follow-up is exactly the gap opposing counsel looks for in a spoliation argument. Hold notification templates should be reviewed with the customer's Legal team before first use, not treated as a generic IT-configured email — the notification language itself often carries legal weight (what it tells the custodian they must and must not do with relevant content) and shouldn't be improvised. Custodians who leave the organization mid-matter need an explicit offboarding-while-on-hold process (mailbox/OneDrive preservation continuing past standard deprovisioning) — this is a frequent gap between the eDiscovery deliverable and the customer's separate IT offboarding workflow, and should be called out explicitly as an integration point.$content$,
'https://learn.microsoft.com/purview/ediscovery-manage-custodians'),

('Collection Query Tuning to Reduce Over-Collection', 'ediscovery', null,
$content$Search conditions (date ranges, sender/recipient, keyword and KQL query, sensitive info type or trainable classifier matches) should be iteratively refined against a statistics-only search before committing to a full collection — running an untuned, overly broad query straight to collection is the most common cause of a review population that's both unnecessarily expensive to review and slower to produce, since every extra document collected is a document someone has to look at or defensibly explain excluding. KQL (Keyword Query Language) conditions support proximity, wildcard, and property-restricted searches well beyond simple keyword matching — recommend investing real time in query refinement with the customer's Legal team before collection, since a well-tuned query is usually the single highest-leverage cost lever in the whole matter. Document and preserve the exact search query and parameters used for each collection as part of the matter record — being able to reproduce and explain exactly how a review population was scoped is a standard defensibility expectation opposing counsel or a court may ask about later.$content$,
'https://learn.microsoft.com/purview/edisc-search-for-content'),

('Export and Load File Formats for Outside Counsel Handoff', 'ediscovery', null,
$content$eDiscovery exports support native file formats, EDRM XML load files (with a Concordance-format DAT and native/text/OPT files), or full case reports, and the correct format depends entirely on what the customer's outside counsel or review platform (Relativity, etc.) actually ingests — confirm the target platform's expected load-file specification with the customer before export, since a mismatched format discovered after a large export is a real time and cost setback. Export size and file-count limits exist per export job; a very large collection may need to be split across multiple export jobs, which should be planned for in the timeline rather than discovered when a single export job fails partway through. Bates numbering and redaction, where required, typically happen downstream in the review platform rather than in the native Purview export — set this expectation clearly so the customer doesn't assume the eDiscovery export step itself produces a court-ready production set.$content$,
'https://learn.microsoft.com/purview/edisc-export-search-results'),

-- information_protection
('Sensitive Information Types: Built-In vs Custom', 'information_protection', null,
$content$Built-in sensitive information types (credit card numbers, SSNs, and 100+ other pre-defined patterns) cover well-structured data with a consistent, documented format and should be the first choice whenever one matches the customer's need, since they require no build or ongoing tuning effort. Custom SITs (regex- or keyword-list-based, optionally combined with a checksum function and confidence-level tuning) are the right tool when a customer has an internally-defined ID format (an employee number, a proprietary account format) that no built-in SIT covers — confidence level and match-count thresholds need real tuning against sample data before go-live, since an under-tuned custom SIT is a common source of either high false positives (blocking legitimate work) or missed matches (the actual compliance gap the SIT was meant to catch). Exact Data Match (see the DLP entry) and trainable classifiers are the next tier up from custom SITs for structured and unstructured data respectively — position custom SITs as the middle ground, not the first or last option, in a scoping conversation about detection accuracy.$content$,
'https://learn.microsoft.com/purview/sensitive-information-type-learn-about'),

('Scoping DLP vs Information Protection Correctly', 'information_protection', null,
$content$Information Protection (sensitivity labels, classification, encryption) governs what content is and how it should be handled; Data Loss Prevention governs what happens when content matching certain criteria tries to move somewhere it shouldn't — the two are complementary and frequently confused as interchangeable during early scoping conversations, and a deliverable should be explicit about which problem each workload is solving for this specific customer. A common, correct combined pattern: sensitivity labels classify and optionally encrypt content, while a DLP policy conditioned on that same label (rather than re-detecting the underlying sensitive info type independently) controls its movement — recommend label-conditioned DLP policies over rebuilding detection logic separately in DLP wherever both workloads are in scope, since it's both less configuration and more consistent for the customer to maintain. Encryption from a sensitivity label persists with the file wherever it goes (including outside the tenant); DLP policy enforcement generally does not travel with the file the same way — make this distinction explicit when a customer asks "will this still be protected once it leaves our environment."$content$,
'https://learn.microsoft.com/purview/information-protection'),

('Information Protection in FedRAMP High / DoD IL4-5 Tenants', 'information_protection', 'Government',
$content$Feature parity for Information Protection capabilities (auto-labeling, trainable classifiers, certain co-authoring scenarios on protected files) has historically lagged behind commercial cloud in GCC High and DoD tenants — verify current feature availability against the Microsoft 365 Government service description for the specific tenant type before committing a deliverable to a capability, rather than assuming commercial-cloud parity. Double Key Encryption and Hold Your Own Key scenarios (see the sensitivity-labels entry) come up disproportionately often in this segment specifically because of data-sovereignty and Microsoft-cannot-decrypt requirements — budget scoping time to clarify which of these the customer's authorizing official actually requires versus assumes they need, since the two mechanisms differ significantly in effort and collaboration trade-offs. Encryption key management for Government tenants may need to align with the customer's own ATO (Authority to Operate) boundary and existing key-management infrastructure — this is a cross-functional conversation with the customer's ISSO, not a configuration decision Purview implementation alone can make.$content$,
'https://learn.microsoft.com/microsoft-365/compliance/offering-fedramp'),

-- communication_compliance
('Detection Conditions and Policy Templates', 'communication_compliance', null,
$content$Communication Compliance policy templates (offensive language, sensitive info sharing, regulatory compliance, conflict of interest) each ship with a starting set of detection conditions that should be tuned against the customer's actual communication patterns before go-live, not left at defaults — an untuned offensive-language policy on a construction or manufacturing customer's internal Teams channels, for example, frequently over-flags industry-standard terminology as a false positive in the first weeks. Machine-learning-based classifiers (versus simple keyword conditions) materially reduce false-positive volume for nuanced categories like harassment or threats, at the cost of needing a representative volume of the customer's own communications to calibrate against — set expectations that ML-classifier-based policies improve over the first weeks of live data rather than being perfectly tuned at launch. Sentiment and named-entity conditions can combine with keyword conditions in a single policy for more precise triggering — recommend layering conditions rather than relying on a single broad keyword list, which is the most common source of reviewer alert fatigue.$content$,
'https://learn.microsoft.com/purview/communication-compliance-policies'),

('Coverage Beyond Native Teams and Exchange', 'communication_compliance', null,
$content$Native coverage extends to Exchange, Teams, and Viva Engage out of the box; third-party communication platforms (Slack, Bloomberg Message, Zoom, and others via Microsoft's communication compliance connectors, or via a Graph-based custom connector) require explicit connector setup and should be scoped as their own line item, not assumed to be covered because "Communication Compliance is enabled." Confirm which of the customer's actual communication channels carry the compliance risk the engagement is meant to address — a financial-services customer whose real regulatory exposure is in Bloomberg chat, for instance, gets limited value from a policy that only covers Teams and Exchange, and scoping should surface this mismatch before build rather than after go-live. Copilot interactions and AI-generated content are themselves a growing detection surface for Communication Compliance policies — this is an increasingly common ask in scoping conversations and worth raising proactively rather than waiting for the customer to ask whether it's covered.$content$,
'https://learn.microsoft.com/purview/communication-compliance-plan'),

('Adaptive Protection Integration for Review Prioritization', 'communication_compliance', null,
$content$Communication Compliance can consume Insider Risk Management's Adaptive Protection risk levels to automatically prioritize review of flagged communications from users already at elevated risk — recommend wiring this up wherever both IRM and Communication Compliance are in scope for the same engagement, since it turns two independently useful signals into a materially better triage mechanism than treating every flagged message with equal priority. This integration requires IRM to already be configured with the relevant indicators feeding Adaptive Protection — sequence the engagement so IRM setup happens before or alongside Communication Compliance tuning if both are in scope, rather than treating them as fully independent workstreams that happen to touch the same content. As with the underlying IRM signal, elevated-risk-driven prioritization should be explained to reviewers as a triage aid, not a verdict — a message from an elevated-risk user still needs the same substantive review as any other flagged item, just sooner.$content$,
'https://learn.microsoft.com/purview/insider-risk-management-adaptive-protection'),

-- cloud_migration
('Hybrid Identity Sequencing Before Mailbox Migration', 'cloud_migration', null,
$content$Directory synchronization (Microsoft Entra Connect or Cloud Sync) and the customer's chosen authentication model (password hash sync, pass-through authentication, or federation) need to be stable and validated well before the first mailbox migration batch runs — a migration wave that starts before identity sync is fully trusted is a common source of hard-to-diagnose access and mail-flow issues that get blamed on the migration tooling when the actual root cause is upstream in identity. Recommend password hash sync with seamless SSO as the default starting point for most customers over federation (ADFS) unless there's a specific existing requirement driving federation, since it has meaningfully less infrastructure to operate and fewer failure points during a migration window. Confirm UPN and primary SMTP address alignment between on-premises AD and the target tenant before migration, not after — mismatches here are individually small but collectively one of the most common sources of migration-week helpdesk ticket volume.$content$,
'https://learn.microsoft.com/entra/identity/hybrid/connect/whatis-hybrid-identity'),

('SharePoint and OneDrive Content Migration at Scale', 'cloud_migration', null,
$content$SharePoint Migration Tool (SPMT) and Migration Manager both move file-share and on-premises SharePoint content into SharePoint Online/OneDrive, but Migration Manager's agent-based, centrally-monitored approach is the better recommendation for a multi-terabyte, multi-source engagement, since SPMT's per-job model doesn't give the same fleet-wide visibility and retry handling at scale. Pre-migration content assessment (file path length limits, unsupported characters, file type restrictions, and orphaned permissions) should run and be remediated as its own phase before migration jobs start — discovering these issues mid-migration turns a planned cutover into an extended, unplanned one. Permissions and sharing links rarely map over cleanly from an on-premises file share's NTFS permission model to SharePoint's sharing model — set the customer's expectation early that a permissions redesign, not a literal one-to-one translation, is usually part of a successful migration, not an optional nice-to-have.$content$,
'https://learn.microsoft.com/sharepointmigration/migration-manager-hub-landing-page'),

('Post-Migration Validation and Legacy Decommission', 'cloud_migration', null,
$content$A migration engagement isn't complete at cutover — a documented validation pass (mail flow, calendar free/busy, mobile device access, a sample of user-reported spot checks) should run for a defined stabilization period before the legacy environment is decommissioned, and this stabilization window should be an explicit line item in the deliverable timeline, not assumed to be zero-length. Coexistence period length (how long legacy and cloud environments run in parallel) is a real cost and risk trade-off the customer needs to make deliberately — too short risks cutting over before issues surface, too long carries ongoing dual-infrastructure cost and complexity; recommend a length proportional to the environment's complexity and the customer's risk tolerance, not a fixed default. Legacy on-premises decommission (retiring old Exchange/SharePoint servers, revoking now-unneeded service accounts and firewall rules) is itself a distinct project with its own security implications if left half-done — flag it as a follow-on deliverable rather than letting it become "someone will get to it eventually."$content$,
'https://learn.microsoft.com/exchange/hybrid-deployment/set-up-hybrid-deployment'),

-- app_modernization
('Power Platform Center of Excellence Adoption', 'app_modernization', null,
$content$The Center of Excellence (CoE) Starter Kit — a set of Power Platform solutions, flows, and dashboards Microsoft publishes and maintains — gives a customer inventory, governance, and adoption-tracking capability across their maker population without building this tooling from scratch, and should be the default recommendation for any customer past the "a few makers building a few apps" stage who doesn't already have equivalent tooling. Recommend starting with the Core Components (inventory and governance) before layering on the Nurture and Governance modules — a customer that tries to adopt the full kit at once typically stalls on the setup complexity before getting value from any of it. The CoE kit itself needs an owning team (typically a Center of Excellence or platform team) to actually act on what it surfaces — deploying the tooling without also scoping who reviews its dashboards and acts on its governance flags produces visibility without governance, which doesn't move the needle on the actual risk (uncontrolled app sprawl) it's meant to address.$content$,
'https://learn.microsoft.com/power-platform/guidance/coe/starter-kit'),

('Dataverse Security Model for Modernized Apps', 'app_modernization', null,
$content$Dataverse's security model (business units, security roles, teams, and field-level security) is meaningfully more granular than a typical Power Apps canvas app built directly on SharePoint or Excel, and modernizing a legacy app onto Dataverse is the right moment to design real role-based access rather than carrying forward an ad hoc permission model from the legacy system. Security roles should be designed around the customer's actual job functions and data-access needs, not simply mirrored one-to-one from an existing AD group structure — a common and avoidable mistake is copying old permission boundaries onto Dataverse's model without questioning whether they still make sense for the redesigned app. Environment strategy (how many Dataverse environments, and which teams/apps live in which) should be decided before app build starts, since moving an app between environments later is real migration effort, not a configuration toggle — this belongs in the app modernization scoping conversation, not deferred to "we'll figure it out."$content$,
'https://learn.microsoft.com/power-platform/admin/wp-security-cheat-sheet'),

('Application Rationalization and Retirement Scoring', 'app_modernization', null,
$content$Before committing to modernize a specific legacy application, run a structured rationalization pass across the customer's full app inventory — scoring each app on business criticality, technical health, user base size, and licensing/support cost — since "modernize everything" is rarely the right answer and a clear minority of a typical legacy portfolio actually justifies the investment; some apps should be retired outright, others left alone. Legacy app retirement criteria (low usage, redundant with a newer platform capability, no remaining technical support, or a clear lower-cost replacement already licensed) give the customer a defensible basis for retirement decisions instead of ad hoc "nobody seems to use this anymore" judgment calls that stall when a hidden dependent surfaces later. Document dependencies (which other systems or manual processes rely on a candidate app) before recommending retirement — an app that looks obviously low-value from usage telemetry alone sometimes turns out to be a critical dependency for a handful of high-value users or a downstream integration nobody flagged during discovery.$content$,
'https://learn.microsoft.com/power-platform/guidance/adoption/application-modernization'),

-- sharepoint
('SharePoint Advanced Management for Governance at Scale', 'sharepoint', null,
$content$SharePoint Advanced Management adds tenant-wide policy controls (site lifecycle management, restricted content discovery, site access review, and data-access governance reporting) that basic SharePoint admin capabilities don't cover, and is the right recommendation as soon as a customer's site count moves from "a manageable few dozen" into the hundreds or thousands, where per-site manual governance stops being realistic. Site lifecycle policies (inactive site detection, automated archival or ownerless-site remediation) address the specific, common problem of site sprawl outliving its original business purpose — recommend enabling these proactively rather than waiting for a customer's audit or security review to surface an unmanageable backlog of ownerless or long-dormant sites. Restricted content discovery limits which sites and files Copilot and enterprise search can surface content from, independent of a site's normal sharing permissions — this is an increasingly relevant control to raise explicitly in any engagement where Copilot rollout is also on the customer's roadmap (see the analytics_ai oversharing-remediation entry).$content$,
'https://learn.microsoft.com/sharepoint/advanced-management'),

('Hub Sites and Site Provisioning Governance', 'sharepoint', null,
$content$Hub sites give a customer shared navigation, branding, and cross-site search/news aggregation across a related group of sites without forcing everything into one giant monolithic site — recommend a hub-and-spoke information architecture over a single large site for any customer organized around multiple departments, regions, or major projects that each need their own site-level permissions boundary. Self-service site creation (via the SharePoint start page or Teams) should be paired with a provisioning governance policy — a naming convention, a default sensitivity label, and (where the customer's scale justifies it) an approval workflow — since unrestricted self-service creation is the most common root cause of the ungoverned site sprawl that SharePoint Advanced Management's lifecycle tooling later has to clean up. Site templates and the PnP provisioning framework can bake governance defaults (permissions structure, default document libraries, required metadata) directly into how new sites get created, which is a more durable fix than relying on after-the-fact policy enforcement alone.$content$,
'https://learn.microsoft.com/sharepoint/hub-site-planning'),

('External Sharing and Guest Access Policy Design', 'sharepoint', null,
$content$SharePoint and OneDrive external sharing settings (anyone links, new-and-existing-guests, existing-guests-only, or fully disabled) should cascade from a single tenant-level default down to more permissive or restrictive site-level overrides only where a specific site's business need justifies deviating from the default — a common design mistake is leaving every site at the same broad tenant default regardless of the sensitivity of what it holds. Anyone links (no sign-in required) carry meaningfully higher risk than authenticated guest links and should default to disabled or short expiration windows for any site handling regulated or confidential content — recommend site owners justify anyone-link use explicitly rather than leaving it available by default across the tenant. Guest access review (via Entra ID access reviews or SharePoint Advanced Management's data access governance reports) should run on a recurring cadence, not just at initial rollout — guest accounts accumulate over time as external collaboration happens, and stale guest access to sensitive sites is a common, quietly growing risk that periodic review is specifically meant to catch.$content$,
'https://learn.microsoft.com/sharepoint/external-sharing-overview'),

-- analytics_ai
('Purview Data Map and Unified Catalog for Analytics Estates', 'analytics_ai', null,
$content$Microsoft Purview's Data Map and Unified Catalog scan and classify data sources across a customer's analytics estate — Fabric, Azure SQL, Azure Data Lake, and increasingly non-Microsoft sources via its growing connector catalog — building a searchable inventory of what data exists, where, and how sensitive it is, which is foundational groundwork before a customer can meaningfully govern or apply sensitivity labels across a large, sprawling analytics environment. Recommend running an initial Data Map scan early in any analytics-governance engagement specifically to surface unknown or undocumented data sources — it's a common and useful discovery step, since most customers' actual data estate is larger and less documented than their own data team initially believes. Classification results from Data Map scans can drive downstream sensitivity labeling and access-policy enforcement on the same data assets, closing the loop between "we know what data we have and how sensitive it is" and "we're actually protecting it accordingly" rather than leaving those as two disconnected initiatives.$content$,
'https://learn.microsoft.com/purview/unified-catalog-overview'),

('Copilot Oversharing Risk Remediation Before Rollout', 'analytics_ai', null,
$content$Microsoft 365 Copilot surfaces content the requesting user already has permission to see — which means any pre-existing oversharing problem (a site with broader access than it should have, a stale "anyone" link, an inherited permission nobody has audited in years) becomes materially more discoverable the moment Copilot is turned on, and should be remediated before rollout, not treated as a Copilot-specific new risk to solve separately. SharePoint Advanced Management's data access governance reports and restricted content discovery controls (see the sharepoint entries) are the primary tools for this remediation pass — recommend running an oversharing assessment as an explicit, scoped pre-rollout phase of any Copilot engagement, with a clear go/no-go gate before broad user rollout rather than launching Copilot in parallel with governance cleanup. This is consistently one of the highest-value, most underestimated line items in a Copilot readiness engagement — customers frequently budget for the AI rollout itself and underestimate the permissions-cleanup effort that has to happen first.$content$,
'https://learn.microsoft.com/copilot/microsoft-365/microsoft-365-copilot-data-oversharing'),

('Fabric Workspace Governance and OneLake Sensitivity Enforcement', 'analytics_ai', null,
$content$Microsoft Fabric workspaces should follow the same deliberate governance design as SharePoint sites — a workspace access model tied to actual team/project boundaries, not ad hoc contributor access granted individually over time — and this should be scoped explicitly alongside capacity planning (see the Fabric capacity-planning entry) rather than treated as a secondary concern once compute sizing is settled. Sensitivity labels applied to Fabric items (a lakehouse, a semantic model, a report) enforce and travel with the data similarly to labels on Office documents, including downstream into Power BI reports built on top of labeled data — recommend applying labels at the OneLake/data-item level early, since retrofitting classification onto an already-large, already-in-use Fabric estate is a much larger effort than establishing labeling discipline from the start. Fabric's admin portal governance settings (tenant switches controlling external sharing, workspace creation, and Copilot-in-Fabric availability) should be reviewed and deliberately set as part of initial rollout, not left at their out-of-the-box defaults, which trend permissive.$content$,
'https://learn.microsoft.com/fabric/governance/governance-overview');
